# arguments to this file:
# - ARCH
# - APPDIR, the place to put executable files
# - OUTDIR, the place to put object files
# - ACTION, build or clean

PARAMS  :=  DEBUG=$(DEBUG) ARCH=$(ARCH) CC=$(CC) AR=$(AR) OBJCOPY=$(OBJCOPY)

build:
	@ true

clean:
	@ true
