name: Kernel unit test

on:
  - push

jobs:

  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: cheskout repo
        uses: actions/checkout@v4

      - name: build unit test
        run: make test

      - name: run unit test
        run: build/test
